// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5PvRovtQWm7F1dSSEXljKAb4pjTR3E1w',
    appId: '1:252170844826:web:63b0636ffc89fb3d287d23',
    messagingSenderId: '252170844826',
    projectId: 'flutterauthen-44c46',
    authDomain: 'flutterauthen-44c46.firebaseapp.com',
    storageBucket: 'flutterauthen-44c46.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUO1WVtCSKLESkl1yCHhTLqYhOcbENf34',
    appId: '1:252170844826:android:0ba82e4da0e7743d287d23',
    messagingSenderId: '252170844826',
    projectId: 'flutterauthen-44c46',
    storageBucket: 'flutterauthen-44c46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxoxoG4_KZgOqUNifFiucPYbL-wEOpY3Y',
    appId: '1:252170844826:ios:26ba67bd81f5ec0b287d23',
    messagingSenderId: '252170844826',
    projectId: 'flutterauthen-44c46',
    storageBucket: 'flutterauthen-44c46.appspot.com',
    iosBundleId: 'com.sakkarin.projAppUITests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxoxoG4_KZgOqUNifFiucPYbL-wEOpY3Y',
    appId: '1:252170844826:ios:7ab9e7a60926d94a287d23',
    messagingSenderId: '252170844826',
    projectId: 'flutterauthen-44c46',
    storageBucket: 'flutterauthen-44c46.appspot.com',
    iosBundleId: 'com.example.onboardingScren.RunnerTests',
  );
}
